### ISSUE TITLE
Algorithm optimisations, wording etc.

### ISSUE THREAD

**Issue by StepanZharychev** [Luciffer007/Educational-projects#1]
Please, proceed with the following steps in order to improve the algorithm quality:

- Add extra parameter which is **order**, you can define it as Enum (asc, desc), and modify logic in order to use this parameter to specify the order of sorting;
`public static double[] BubbleSort(double[] array)`
- Define **temp** variable in place instead of doing empty definition;
`double temp;`
- Change 'swap them' comment to 'Swap elements which passed order condition', first one is meaningless;
- (Optional) Check how to make the performance better and speed up the sorting;

**Comment by Luciffer007** [comment]
Okay. The necessary changes were made.
