### ISSUE TITLE
Issues - 10/09

### ISSUE THREAD

**Issue by StepanZharychev** [Luciffer007/Educational-projects#2]
_Typo/Parameters:_
- `SortingAlgorithms.BubbleSort(sortArray, direction);`:
Change **sortArray** to **sort**. (code and readme both) Avoid such parameter naming, because 'sort' prefix is redundant - your method is already responsible for sorting, no need to mention it one more time;
- `SortingAlgorithms.QuickSort(sortArray, firstElement, lastElement);;`
The same as above, also remove duplicate semicolon in readme.
- `BinarySortTree binaryTree = new BinarySortTree(rootValue);`
**rootValue** to **value**, the same reason, it's already obvious, that root is a value.
- `binaryTree.Insert(insertionValue, binaryTree.Root);`
     `binaryTree.Insert(insertionValueArray);`
**insertionValue** to **nodeValue**.
**insertionValueArray** to **nodeValues**.
- `binaryTree.Find(searchedValue, binaryTree.Root);`
**searchedValue** to **nodeValue**.
- `binaryTree.Delete(deletionNode);`
**deletionNode** to **nodeValue**.

_Code:_
- ```if (node.Left == null)
                {
                    node.Left = new BinaryTreeNode();
                    node.Left.Data = number;
                    node.Left.Parent = node;
                }
                // Or go down the left branch to the node below and repeat the operation.
                else
                    Insert(number, node.Left);
Please add curve brackets for **else** condition parts everywhere, where you have it for **if**, it looks very inconsistent.

Also create a separate branch for those fixes, so I can do the review inside pull request.

**Comment by Luciffer007** [comment]
The necessary changes were made and placed in a branch general_fixed_branch

**Comment by StepanZharychev** [comment]
Fixed and closed in https://github.com/Luciffer007/Educational-projects/pull/3
